title: PetitBon
email: miya850604@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Records of my life, including programming, animation, and some notes.
  Now I live in the Netherlands for exchanging program :D.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Miya
author-pic: adam-face.jpg
about-author: Hi, this is Miya. I am an software developer, hoping to be an animator one day.

# Contact links
email: miya850604@gmail.com
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: Miyaya # Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: 'journal.petit'
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
